### ISSUE TITLE
pipreqsnb with ipyparallel

### ISSUE THREAD

**Issue by thmoeller** [ivanlen/pipreqsnb#12]
I have a notebook using ipythons parallel features.

this includes a parallel import of packages like this

    with rc[:].sync_imports():
        import pandas as pd
        import cx_Oracle
        import csv
        import datetime
        from calendar import monthrange
        import glob
        from io import StringIO
        from sqlalchemy import create_engine
        import psycopg2

Now pipreqsnb complains about the indention of the import statements, which are totally correct and working in this case.

      File "<unknown>", line 3
        import pandas as pd
        ^
    IndentationError: unexpected indent

Any workaround for this?

**Comment by ivanlen** [comment]
Hi @thmoeller, I think this bug is related with #11 .
Importing code from inside functions or with indentations seems to break `pipreqs`. Since this library is a wrapper of `piprqes` we also have this problem.

I think that there are some hacks to fix this issue from this library instead of trying to change the behavior of `pipreqs`.
I will try to provide a fix in the following days.

Cheers,

**Comment by ivanlen** [comment]
Hey

**Comment by ivanlen** [comment]
Hey @thmoeller, would you mind updating to version 2.2 and see if now it is working fine?

**Comment by thmoeller** [comment]
Works perfectly in version 2.2.

Thanks for solving this issue
