### ISSUE TITLE
Fails when there is a space in the path to the project directory

### ISSUE THREAD

**Issue by DrJohnWagner** [ivanlen/pipreqsnb#24]
I have a project whose path contains a space. The project uses a venv installed in the project home. I installed pipreqsnb in that venv and then tried to run. This should be enough to reproduce. (Sorry I don't have time to debug and submit a PR!)

% cd "Machine Learning"
% cd ProjectName
% python -m venv venv
% source venv/bin/activate
% pwd
/Users/john/Machine Learning/ProjectName
% pipreqsnb .
zsh: /Users/john/Machine Learning/ProjectName/venv/bin/pipreqsnb: bad interpreter: "/Users/jmwagner/Machine: no such file or directory

**Comment by ivanlen** [comment]
Hi. 
I tried to reproduce your issue. The problem is not `pipreqsnb` but the space in your env path.
When I was trying to reproduce the issue I encounter the same error when trying to use pip:
```
» pip install . -e
zsh: /Users/xxyy/coding_projects/env with spaces/bin/pip: bad interpreter: /Users/xxyy/coding_projects/env: no such file or directory
```

I guess that you have to create a new env without spaces in order to be able to run commands such as `pip`, `pipreqsnb` or `pipreqs`.
