### ISSUE TITLE
Syntax Error

### ISSUE THREAD

**Issue by a-r-j** [ivanlen/pipreqsnb#8]
Hiya, I'm getting the following syntax error:

```
Traceback (most recent call last):
  File "/home/arj39/anaconda3/bin/pipreqsnb", line 8, in <module>
    sys.exit(main())
  File "/home/arj39/anaconda3/lib/python3.7/site-packages/pipreqsnb/pipreqsnb.p
y", line 85, in main
    imports += get_import_string_from_source(source)
  File "/home/arj39/anaconda3/lib/python3.7/site-packages/pipreqsnb/pipreqsnb.py", line 23, in get_import_string_from_source
    tree = ast.parse(source)
  File "/home/arj39/anaconda3/lib/python3.7/ast.py", line 35, in parse
    return compile(source, filename, mode, PyCF_ONLY_AST)
  File "<unknown>", line 18
    !mkdir $output_dir
    ^
SyntaxError: invalid syntax
```

**Comment by ivanlen** [comment]
Hi @a-r-j, thank you for reporting an issue.

It seems to me that the problem comes because of the prefix `!` in iPython that allows to run shell commands.
For the moment if you are in a hurry I can imagine that if you comment the line that has `!` or lines with magic commands everything will work fine.

Tomorrow I will try to reproduce this issue and provide a fix for it.

Cheers,

**Comment by ivanlen** [comment]
Hi @a-r-j , I am not being able to reproduce the issue.

Could you please let me know which versions of `pipreqsnb` are you using, which version of `python` and if it is possible provide me a minimal example to reproduce the issue.

Before that check if you are using the version 0.1.3 of pipreqsnb. If not, upgrade it first and try to see if the error persists.

Cheers,
